package discover

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func writeTree(t *testing.T, files map[string]string) string {
	t.Helper()
	root := t.TempDir()
	for name, body := range files {
		p := filepath.Join(root, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return root
}

func outputs(units []Unit) []string {
	out := make([]string, 0, len(units))
	for _, u := range units {
		out = append(out, u.Output)
	}
	return out
}

func TestScanGroupsByDirectoryAndMirrorsTheTree(t *testing.T) {
	root := writeTree(t, map[string]string{
		"main.go":                     "package main\n",
		"internal/billing/charge.go":  "package billing\n",
		"internal/billing/refund.go":  "package billing\n",
		"internal/config/config.go":   "package config\n",
		"internal/config/config.md":   "not source\n",
		"internal/billing/README.txt": "not source\n",
	})

	units, err := Scan(Options{Root: root, Language: "go", BehaviorDir: "behaviors"})
	if err != nil {
		t.Fatalf("Scan: %v", err)
	}

	want := []string{
		"behaviors/internal/billing.md",
		"behaviors/internal/config.md",
		"behaviors/" + filepath.Base(root) + ".md",
	}
	got := outputs(units)
	// Sorted by output path, and the root unit is named after the project.
	if len(got) != 3 {
		t.Fatalf("got %d units, want 3: %v", len(got), got)
	}
	for _, w := range want {
		if !contains(got, w) {
			t.Errorf("missing unit %q, got %v", w, got)
		}
	}
	for _, u := range units {
		if u.Dir == "internal/billing" {
			if len(u.Files) != 2 {
				t.Errorf("billing should hold both sources, got %v", u.Files)
			}
			if u.Files[0] != "internal/billing/charge.go" {
				t.Errorf("files should be sorted, got %v", u.Files)
			}
			if u.Bytes == 0 {
				t.Error("unit should carry the size of its sources")
			}
		}
	}
}

func TestScanLeavesOutWhatIsNotProductCode(t *testing.T) {
	root := writeTree(t, map[string]string{
		"app/service.go":            "package app\n",
		"app/service_test.go":       "package app\n",
		"app/mock.pb.go":            "package app\n",
		"app/zz.go":                 "// Code generated by tool. DO NOT EDIT.\npackage app\n",
		"vendor/dep/dep.go":         "package dep\n",
		"node_modules/x/index.go":   "package x\n",
		".hidden/thing.go":          "package hidden\n",
		"testdata/sample.go":        "package testdata\n",
		"behaviors/app.md":          "# app\n",
		"behaviors/nested/spec.go":  "package nested\n",
		"build/generated_thing.go":  "package build\n",
		"internal/tests/helper.go":  "package tests\n",
		"internal/keep/keep.go":     "package keep\n",
		"internal/skipme/skip.go":   "package skipme\n",
		"internal/keep/keep_ok.go":  "package keep\n",
		"internal/keep/notes.md":    "# notes\n",
		"internal/keep/keep_it.txt": "x\n",
	})

	units, err := Scan(Options{
		Root: root, Language: "go", BehaviorDir: "behaviors", Exclude: []string{"skipme"},
	})
	if err != nil {
		t.Fatalf("Scan: %v", err)
	}

	var files []string
	for _, u := range units {
		files = append(files, u.Files...)
	}
	want := []string{"app/service.go", "internal/keep/keep.go", "internal/keep/keep_ok.go"}
	if len(files) != len(want) {
		t.Fatalf("scanned %v, want %v", files, want)
	}
	for _, w := range want {
		if !contains(files, w) {
			t.Errorf("missing %q, got %v", w, files)
		}
	}
}

func TestScanIncludeTestsKeepsThem(t *testing.T) {
	root := writeTree(t, map[string]string{
		"app/service.go":      "package app\n",
		"app/service_test.go": "package app\n",
	})

	units, err := Scan(Options{Root: root, Language: "go", BehaviorDir: "behaviors", IncludeTests: true})
	if err != nil {
		t.Fatalf("Scan: %v", err)
	}
	if len(units) != 1 || len(units[0].Files) != 2 {
		t.Fatalf("--include-tests should keep the test file, got %+v", units)
	}
}

func TestScanPathsNarrowTheSearch(t *testing.T) {
	root := writeTree(t, map[string]string{
		"a/one.go": "package a\n",
		"b/two.go": "package b\n",
		// A directory normally skipped is still scanned when asked for by name.
		"build/three.go": "package build\n",
	})

	units, err := Scan(Options{
		Root: root, Language: "go", BehaviorDir: "behaviors", Paths: []string{"b", "build"},
	})
	if err != nil {
		t.Fatalf("Scan: %v", err)
	}
	got := outputs(units)
	if len(got) != 2 || !contains(got, "behaviors/b.md") || !contains(got, "behaviors/build.md") {
		t.Fatalf("got %v, want the two requested directories", got)
	}
}

func TestScanGroupFileWritesOneSpecPerFile(t *testing.T) {
	root := writeTree(t, map[string]string{
		"web/handler.js":  "export const a = 1\n",
		"web/handler.jsx": "export const b = 2\n",
		"web/router.js":   "export const c = 3\n",
	})

	units, err := Scan(Options{
		Root: root, Language: "javascript", BehaviorDir: "behaviors", Group: GroupFile,
	})
	if err != nil {
		t.Fatalf("Scan: %v", err)
	}
	got := outputs(units)
	// handler.js and handler.jsx share a stem, so both keep their extension
	// rather than one overwriting the other.
	want := []string{"behaviors/web/handler_js.md", "behaviors/web/handler_jsx.md", "behaviors/web/router.md"}
	if len(got) != len(want) {
		t.Fatalf("got %v, want %v", got, want)
	}
	for _, w := range want {
		if !contains(got, w) {
			t.Errorf("missing %q, got %v", w, got)
		}
	}
}

func TestScanRejectsWhatItCannotRead(t *testing.T) {
	root := writeTree(t, map[string]string{"a/one.go": "package a\n"})

	if _, err := Scan(Options{Root: root, Language: "cobol", BehaviorDir: "behaviors"}); err == nil {
		t.Error("a language katana has no conventions for should be an error, not an empty scan")
	}
	if _, err := Scan(Options{Root: root, Language: "go", Group: "package"}); err == nil {
		t.Error("an unknown grouping should be reported")
	}
	if _, err := Scan(Options{Root: root, Language: "go", Paths: []string{"nope"}}); err == nil {
		t.Error("a path that is not there should be reported")
	}
}

func TestScanFindsNothing(t *testing.T) {
	root := writeTree(t, map[string]string{"README.md": "# hi\n"})
	units, err := Scan(Options{Root: root, Language: "go", BehaviorDir: "behaviors"})
	if err != nil {
		t.Fatalf("Scan: %v", err)
	}
	if len(units) != 0 {
		t.Errorf("got %v, want no units", outputs(units))
	}
}

func TestPromptStatesTheFilesAndTheFormat(t *testing.T) {
	p := BuildPrompt(Request{
		Unit: Unit{
			Name:   "internal/billing",
			Dir:    "internal/billing",
			Files:  []string{"internal/billing/charge.go"},
			Output: "behaviors/internal/billing.md",
		},
		Language: "go",
	})

	for _, want := range []string{
		"behaviors/internal/billing.md",
		"internal/billing/charge.go",
		SkipMarker,
		"observable behavior",
	} {
		if !strings.Contains(p, want) {
			t.Errorf("prompt is missing %q", want)
		}
	}
	if strings.Contains(p, "Existing specification") {
		t.Error("a new behavior file has no existing specification to show")
	}
}

func TestPromptShowsTheSpecificationBeingUpdated(t *testing.T) {
	p := BuildPrompt(Request{
		Unit:             Unit{Name: "app", Files: []string{"app/a.go"}, Output: "behaviors/app.md"},
		Language:         "go",
		ExistingBehavior: "# App\n\n- Hand-written statement.\n",
	})
	if !strings.Contains(p, "Existing specification") || !strings.Contains(p, "Hand-written statement.") {
		t.Error("an update should show the harness what is already written")
	}
}

func contains(list []string, want string) bool {
	for _, s := range list {
		if s == want {
			return true
		}
	}
	return false
}
