package report

import (
	"bytes"
	"html/template"
	"os"
	"path/filepath"
	"strconv"
	"time"
)

type ReadinessStage struct {
	Name     string
	OK       bool
	Error    string
	Duration time.Duration
}

type Readiness struct {
	Project, Root, Version string
	StartedAt              time.Time
	Ready                  bool
	Coverage               float64
	Stages                 []ReadinessStage
	Reason                 string
	Improvements           []string
}

var readinessPage = template.Must(template.New("readiness").Funcs(template.FuncMap{
	"dur": formatDuration,
	"pct": func(v float64) string { return formatPercent(v) },
}).Parse(`<!doctype html><html><head><meta charset="utf-8"><title>Katana release readiness</title>
<style>body{font:16px system-ui;max-width:800px;margin:40px auto;color:#222}.ready{color:#16803c}.not-ready{color:#b42318}table{border-collapse:collapse;width:100%}td{padding:10px;border-bottom:1px solid #ddd}.ok{color:#16803c}.bad{color:#b42318}</style></head><body>
<h1 class="{{if .Ready}}ready{{else}}not-ready{{end}}">{{if .Ready}}Release ready{{else}}Not release ready{{end}}</h1>
<p><strong>{{.Project}}</strong> · coverage <strong>{{pct .Coverage}}</strong></p>
{{if .Reason}}<h2>Why</h2><p>{{.Reason}}</p>{{end}}
{{if .Improvements}}<h2>Improvements</h2><ul>{{range .Improvements}}<li>{{.}}</li>{{end}}</ul>{{end}}
<table>{{range .Stages}}<tr><td>{{.Name}}</td><td class="{{if .OK}}ok{{else}}bad{{end}}">{{if .OK}}passed{{else}}failed: {{.Error}}{{end}}</td><td>{{dur .Duration}}</td></tr>{{end}}</table>
<p>Generated by katana {{.Version}}.</p></body></html>`))

func formatPercent(v float64) string {
	return strconv.FormatFloat(v, 'f', 1, 64) + "%"
}

func (r Readiness) WriteHTML(dir string) (string, error) {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	var b bytes.Buffer
	if err := readinessPage.Execute(&b, r); err != nil {
		return "", err
	}
	path := filepath.Join(dir, "readiness-"+r.StartedAt.Format(FileTimeLayout)+".html")
	if err := os.WriteFile(path, b.Bytes(), 0o644); err != nil {
		return "", err
	}
	return path, nil
}
